apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: database-compactor
    app.kubernetes.io/instance: thanos-compact
    app.kubernetes.io/name: thanos-compact
    app.kubernetes.io/version: master-2020-08-11-2ea2c2b7
  name: thanos-compact
  namespace: thanos
